### ISSUE TITLE
Text ineligible in some slides of FEA documentation

### ISSUE THREAD

**Issue by der-coder** [opensimsa/opensim#1]
Reviewing the provided documentation, some slides have the issue that text lines cover other pieces of text, resulting in documentation that cannot be read.

Currently the issue has been identified for:
- Slides 7, 8, and 9 in [https://github.com/opensimsa/opensim/blob/master/Documentation/FEA/TJunction/1_TJunctionGeometry.pdf](ur)
- Slides 26 and 27 in [https://github.com/opensimsa/opensim/blob/master/Documentation/FEA/TJunction/2_TJunctionStaticFemModel.pdf](url) 
- Slides 17 and  18 in [https://github.com/opensimsa/opensim/blob/master/Documentation/FEA/TJunction/3_TJunctionSteadyStateThermomechanicalFemModel.pdf](url)
- Slide 41 in [https://github.com/opensimsa/opensim/blob/master/Documentation/FEA/BasicSphericalHeader/HeaderFromPrimitives.pdf](url)
- Slides 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, and 22 in  [https://github.com/opensimsa/opensim/blob/master/Documentation/FEA/AdvancedSphericalHeader/2_SphericalHeaderFem.pdf](url)

Tested for online view with Firefox 54 and local file downloades and opened with Okular.

**Comment by oliveroxtoby** [comment]
Unfortunately I could not reproduce this.
