### ISSUE TITLE
Edit Properties and run solvers issues

### ISSUE THREAD

**Issue by Remcatfoil** [opensimsa/opensim#2]
Hi,
I am testing the cfd workbench  using the elbow tuto 1
Prerequisite: freecad 0.17 CFD + BlueCFD-core 2016 installed on windows 10.
My model is ok, i sketched the elbow, applied the boudary conditions, and i did the mesh without any difficulties.
But, i have an unicode error arrising when I write the case in the analysis control panel.
Output says:
0.0: Checking dependencies...
0.0: OpenFOAM case writer is called
0.0: Error writing case:
0.0: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)
0.0: Write case setup file failed

I am stuck here. Any ideas to solve this error?
Many Thanks,
Remy

**Comment by oliveroxtoby** [comment]
Please see https://forum.freecadweb.org/viewforum.php?f=37&sid=3d90858d2ff441bd10475a693b55643a
