### ISSUE TITLE
CFD Tutorial 2a failing

### ISSUE THREAD

**Issue by bunnitech** [opensimsa/opensim#3]
I've done and redone this tutorial from scratch 4 times, restarting FreeCAD between. Tutorial 1 works fine, Tutorial 2a fails every time however with the following output: (github isn't allowing line breaks, sorry for formatting)
`0.0: Checking dependencies...
0.0: Case writer called
1.2: Write case is completed
0.2: Solver started
47.7: OpenFOAM IO error: inconsistent patch and patchField types for file: C:/Users/xxxx/AppData/Local/Temp/case/0/U.boundaryField.defaultFaces from line 58 to line 19.
47.9: Simulation exited with error
`
Additionally, at the mesh refinement step, I see no refinement of the central region around Cube001 in the display mesh... I see no errors in the python console, it seems to be working but isn't. The error states `from line 58 to line 19` which is confusing. The referenced section contains the following:
`    defaultFaces
    {
        type        slip;
        value       $internalField;
    }`
Any idea what's going on here? I noticed the tutorial version of the workbench looks very different and has different options from the current version (I installed from the FreeCAD add-ons window today). Has anyone checked the tutorials against the current version?

**Comment by oliveroxtoby** [comment]
We test against the supplied .FCMacro files, but unfortunately the tutorial instructions are quite out of date now. We would need community assistance to update the slides. Let me know if you are willing to help.
