### ISSUE TITLE
UAV case could not run on

### ISSUE THREAD

**Issue by skunk69** [opensimsa/opensim#5]

**Comment by skunk69** [comment]
UAV case could not run on the latest FreecCAD 0.19pre,because the part wotkbench doesn't support the boolean operation of non-solids.

**Comment by oliveroxtoby** [comment]
We have modified the procedure for setting up this case, and this is reflected in the FCMacro file. The slides, unfortunately, are outdated at the moment. Hopefully the new procedure will be clear from looking at / running the macro.

**Comment by skunk69** [comment]
OK！thank you very much！ 好的，谢谢！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Oliver&amp;nbsp;Oxtoby&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月15日(星期二) 晚上7:33
收件人:&nbsp;&quot;opensimsa/opensim&quot;<opensim@noreply.github.com&gt;;
抄送:&nbsp;&quot;skunk69&quot;<28485690@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [opensimsa/opensim] UAV case could not run on (#5)
